{ config, pkgs, lib, ... }:

let
  dotfiles = "${config.home.homeDirectory}/code/tobmoeller/dotfiles";
  php = pkgs.php85.buildEnv {
    extensions = ({ enabled, all}: enabled ++ (with all; [
      redis
      gnupg
      yaml
      xdebug
      # imagick
      # pcov
      # rdkafka
      # mongodb
    ]));
    extraConfig = ''
      memory_limit = 500M
      xdebug.mode=coverage
    '';
  };
in {
  imports = [
    ./tmux.nix
    ./herdr.nix
    ./zsh.nix
    ./nvim.nix
    ./claude-skills.nix
    ./claude-settings.nix
  ];

  # https://nixos.org/manual/nixpkgs/stable/#sec-allow-unfree
  nixpkgs.config.allowUnfreePredicate = pkg: builtins.elem (lib.getName pkg) [
    "intelephense"
    # "ngrok"
    "vim-visual-star-search"
    "vim-highlightedyank"
  ];

  home.packages = with pkgs; [
    hyperfine
    meslo-lgs-nf # nerd font for powerlevel10k theme
    # timewarrior
    jq # command line json processor
    # minikube

    php
    php.packages.composer

    nodejs_24
    python3

    herdr

    # LSP packages
    phpactor
    typescript
    typescript-language-server
    vue-language-server
    tailwindcss-language-server
    intelephense
    pyright
  ] ++ lib.optionals stdenv.isLinux [
    # Clipboard backends. herdr, tmux and Claude Code all copy via a native
    # tool (wl-copy on Wayland, xclip on X11/XWayland) before any OSC 52
    # fallback — without one, copy fails silently. Linux-only (these packages
    # don't exist on darwin). NOTE: herdr and Claude Code cache clipboard-tool
    # detection at startup, so restart both after first installing these.
    wl-clipboard   # wl-copy/wl-paste — Wayland (your current session)
    xclip          # X11/XWayland fallback; also what tmux.conf's copy-yank uses
  ];

  home.file = {
    # ".screenrc".source = dotfiles/screenrc;
    ".npmrc".text = "prefix=${config.home.homeDirectory}/.npm-global";

    ".local/bin/t".source =
      config.lib.file.mkOutOfStoreSymlink "${dotfiles}/home-manager/packages/scripts/t";
    ".local/bin/wt".source =
      config.lib.file.mkOutOfStoreSymlink "${dotfiles}/home-manager/packages/scripts/wt";

    # .claude/settings.json is generated by ./claude-settings.nix (base + host
    # permission overlays), so it is intentionally not symlinked here.
    ".claude/CLAUDE.md".source =
      config.lib.file.mkOutOfStoreSymlink "${dotfiles}/home-manager/packages/config/claude/CLAUDE.md";
    ".claude/hooks/bash-guard.sh".source =
      config.lib.file.mkOutOfStoreSymlink "${dotfiles}/home-manager/packages/config/claude/hooks/bash-guard.sh";
    ".claude/hooks/canary-check.sh".source =
      config.lib.file.mkOutOfStoreSymlink "${dotfiles}/home-manager/packages/config/claude/hooks/canary-check.sh";
    ".claude/statusline.sh".source =
      config.lib.file.mkOutOfStoreSymlink "${dotfiles}/home-manager/packages/config/claude/statusline.sh";
  };

  # Claude Code skills are linked per-skill by ./claude-skills.nix. Every host
  # gets the "common" group by default; hosts add their own group on top, e.g.:
  #   claudeSkillGroups = [ "common" "red" ];   # red's skills override common's
  claudeSkillGroups = [ "common" ];

  home.sessionPath = [
    "$HOME/.local/bin"
    "$HOME/.composer/vendor/bin"
    "$HOME/.config/composer/vendor/bin"
    "$HOME/.npm-global/bin"
    "$HOME/bin"
  ];

  home.sessionVariables = {
    VUE_PLUGIN_PATH = "${pkgs.vue-language-server}/lib/node_modules/@vue/language-server";
    # EDITOR = "emacs";
  };

  programs.git = {
    enable = true;
    settings = {
      alias = {
        s = "status -sb";
        st = "status";
        ci = "commit";
        co = "checkout";
        nah = "!git reset --hard && git clean -df";
        alias = "! git config --get-regexp ^alias\. | sed -e s/^alias\.// -e s/\ /\ =\ /";
      };
      user.name = lib.mkDefault "TobMoeller";
      user.email = lib.mkDefault "tobiasmoellerw@t-online.de";

      push.autoSetupRemote = true;
      init.defaultBranch = "main";
    };
    ignores = [
      "_ide_*"
      ".phpstorm*"
    ];
  };

  # programs.direnv = {
  #   enable = true;
  #   enableZshIntegration = true;
  #   nix-direnv.enable = true;
  # };

  programs.ripgrep = {
    enable = true;
  };

  programs.fzf = {
    enable = true;
  };
}
